version: '3.8'

services:
  fluxton_db:
    image: postgres:latest
    container_name: fluxton_db
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}  # Fallback to 'postgres' if not set
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-yourpassword}  # Fallback to 'yourpassword' if not set
      - POSTGRES_DB=${DATABASE_NAME:-fluxton_db}  # Fallback to 'fluxton_db' if not set
    volumes:
      - fluxton_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fluxton_network

networks:
  fluxton_network:
    driver: bridge

volumes:
  fluxton_db_data:
