basePath: /v2
host: fluxton.io/api
info:
  contact:
    email: chief@fluxton.io
    name: API Support
    url: http://github.com/fluxton-io/fluxton
  description: Fluxton is backend as-a-service platform that allows you to build,
    deploy, and scale applications without managing infrastructure.
  title: Fluxton API
  version: "1.0"
paths: {}
swagger: "2.0"
